### ISSUE TITLE
Slow edge creation in Docker

### ISSUE THREAD

**Issue by jarno-steeman** [orientechnologies/orientdb#5783]
Experiencing quite the poor performance when creating edges, vertices are no problem. I'm only running 1 OrientDB (v2.1.10) container in Docker (v1.9.1) on OS X and doing all this in OrientDB Studio:

As a test i've inserted 400 vertices and then run this query: `CREATE EDGE Friend FROM (SELECT FROM Users) TO #9:1` which is taking very long to finish. Just creating 400 edges takes about 5 seconds. 

It seems to relate to Docker because if I run OrientDB directly on OS X and do the exact same thing it does go fast.

Any tips?

EDIT: these are the options im running the container with:
```
command: /orientdb/bin/server.sh -Xmx700m -Dstorage.diskCache.bufferSize=1200 -DridBag.embeddedToSbtreeBonsaiThreshold=2147483647
mem_limit: 2g
```

**Comment by robfrank** [comment]
Hi, on osx docker is executed inside a virtualBox VM. Could you please post the command you use to launch the container? Do you configure the container with volumes? Thanks

**Comment by jarno-steeman** [comment]
It's part of a composition, this is the full configuration:
```
orientdb1:
    image: orientdb/orientdb
    container_name: orientdb1
    command: /orientdb/bin/dserver.sh -Xmx700m -Dstorage.diskCache.bufferSize=1200 -DridBag.embeddedToSbtreeBonsaiThreshold=2147483647
    mem_limit: 2g
    volumes:
        - ./docker/orientdb/config1:/orientdb/config
        - ./docker/orientdb/databases1:/orientdb/databases
        - ./docker/orientdb/backup1:/orientdb/backup
    ports:
        - "2424:2424"
        - "2480:2480"
```
