### ISSUE TITLE
How to create a local database from Scala for testing?

### ISSUE THREAD

**Issue by LianaN** [orientechnologies/orientdb#8249]
## Issue  
I am using OrientDB on docker. 

```
  orientdb:
      image: orientdb:2.2.33
      container_name: orientdb
      ports:
        - "2424:2424"
        - "2480:2480"
      environment:
        - "ORIENTDB_ROOT_PASSWORD=123"
      restart: "no"
```

I wonder how can I create a graph in Scala.

```
val uri="remote:127.0.0.1/GRAPH_TEST"
val username="root"
val password="123"
val factory: OrientGraphFactory = new OrientGraphFactory(uri,username,password)
val graph = factory.getTx()
```

If I run this code, I get the error:

`Exception in thread "main" com.orientechnologies.orient.core.exception.OConfigurationException: Database 'GRAPH_TEST' is not configured on server (home=/orientdb/databases/)`
