### ISSUE TITLE
Deploy orientDB with Ansible on a computer with no Internet

### ISSUE THREAD

**Issue by edmondboulet** [orientechnologies/orientdb#8374]
### OS: linux 

Hello, I have a little question.

I'm trying to deploy multiple cluster on a hand full of computer but those computer don't have access to the internet. So when they try to Download OrientDB, the task fail.

I'm using Ansible with migibert tool ( [from the doc](https://orientdb.com/docs/3.0.x/gettingstarted/Tutorial-Installation.html#use-ansible) ).

Ans this is my current playbook :

```
- hosts: orientdb-servers
  become: yes
  vars:
    orientdb_version: 3.0.2
    orientdb_enable_distributed: true
    orientdb_distributed:
      hazelcast_network_port: 2434
      hazelcast_group: orientdb
      hazelcast_password: orientdb
      multicast_enabled: True
      multicast_group: 235.1.1.1
      multicast_port: 2434
      tcp_enabled: False
      tcp_members: []
    orientdb_users:
      - name: root
        password: root
  roles:
  - role: migibert.orientdb
```

What are my options ?

Thanks.

**Comment by edmondboulet** [comment]
I'm going to answer to my own question as I found a quick fix working well.
In /etc/ansible/roles/migibert.orientdb/tasks/install.yml  replace the first task

```
- name: Download OrientDB tarball
  get_url:
    url: server URL
    dest: "/tmp/orientdb-{{orientdb_version}}.tar.gz"
```

by 

```
- name: Download OrientDB tarball
  copy:
    src: /home/vagrant/Ansible/OrientDB/orientdb-{{orientdb_version}}.tar.gz
    dest: /tmp/orientdb-{{orientdb_version}}.tar.gz
    owner: root
    group: root
    mode: 0644
```

and make sure you have an orientDB package at the specified source.
Now ansible will grab the package from your local machine and will install it on your server.
This may result in some name changes so make sure the folder name one extracted is orientdb-community-{{orientdb_version}}.
