### ISSUE TITLE
'PLOCAL' was not found

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#9023]
### Installed via Docker, `docker-compose.yml` :
```
version: '3'

services:
  orientdb:
    image: orientdb
    ports:
      - 2424:2424
      - 2480:2480
    environment:
      ORIENTDB_ROOT_PASSWORD: 'blabla'
    volumes:
      - ./orientdb/backup:/orientdb/backup
```

### Now I need to create a db : 

1.  ```$ sudo docker run --rm -it orientdb /orientdb/bin/console.sh```
2. ```orientdb> CREATE DATABASE PLOCAL:/databases/testdb```

And getting : 

```
orientdb> CREATE DATABASE PLOCAL:/databases/testdb

Error: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: the engine 'PLOCAL' was not found. URL was: PLOCAL:/databases/testdb. Registered engines are: ["embedded","remote"]
```

What do I miss here, please ? Thanks
