### ISSUE TITLE
Database is locked on Master while Replica downloads data (async mode)

### ISSUE THREAD

**Issue by sirmax123** [orientechnologies/orientdb#9434]
### Java Version:
```
java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM (build 25.272-b10, mixed mode)
```
### OS: Docker container, orientdb:3.0.34

My setup: 
odb1 - Standalone Master node, 2 databases ~3Gb each
odbB - just added Replica node (need it because automatic-backup plugin locks database)

I'm trying to add the REPLICA node to the existing Master Node (only one master), and when the replica is added, databases are in read-only mode while the replica node downloads data.

## Expected behavior  
No locks expected in async mode.

## Actual behavior  
```
orientdb {db=rigel}> INSERT INTO Test_mmazur(id, name, age) values (1, 'tttt', 1);
Inserted record '[Test_mmazur#211:4023{id:1,name:tttt,age:1} v1]' in 97.334999 sec(s).
```
Insert took 97 seconds and finished only after Replica downloaded all data.

## Steps to reproduce  
1. Setup a standalone database.

2. Stop database, add `hazelcast.xml`
```
      <tcp-ip enabled="true">
        <member>master-node.domain.tld</member>
        <member>replica-node.domain.tld</member>
      </tcp-ip>
```
Configure `default-distributed-db-config.json `
"executionMode": "asynchronous",
odb1 - Standalone node
odbB (B here means "backup") -Replica node
```
{
  "replication": true,
  "hotAlignment": true,
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": 1,
  "executionMode": "asynchronous",
  "readYourWrites": true,
  "newNodeStrategy": "static",
  "servers":{
    "odb1": "MASTER",
    "odbB": "REPLICA"
  },
  "clusters": {
    "*": {
      "servers": ["odb1", "odbB"]
    }
  }
}
```

Node odbB has the same configuration.
Both nodes odb1 and odbB are started using docker (Examle only for node odb1)

```
version: '3'
services:
  orientdb:
    container_name: odb1
    hostname: odb1.fred.in.pn.telstra.com
    image: orientdb:3.0.34
    command: dserver.sh debug
    volumes:
<data, logs and configs are on volumes>
    environment:
      ORIENTDB_SETTINGS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava
      ORIENTDB_NODE_NAME: "odb1"
      ORIENTDB_OPTS_MEMORY: "-Xms4G -Xmx4G"
    network_mode: host
    restart: always
    logging:
<skipped>
    extra_hosts:
      "odb1": 127.0.0.1
```

3. Start both Master and replica nodes.
4. Check logs, see messages like this
```
2020-11-05 11:17:19:599 INFO  [odbB] - writing chunk #19 offset=0 size=5.10MB [OSyncReceiver]
```
5. Try to use DB
 - can read
 - can't insert data until sync is finished.
